In [ ]:
# Save in Colab
import numpy as np
a = np.arange(15).reshape(3, 5)
a < 10

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [False, False, False, False, False]])

In [ ]:
print(a.shape)
print(a.ndim)
print(a.dtype.name)
print(a.itemsize)
print(a.size)
print(a.data)
print(type(a))


(3, 5)
2
int64
8
15
<class 'numpy.ndarray'>


In [ ]:
a = np.array([2, 3, 4])
a
c = np.array([[1, 2], [3, 4]], dtype=complex)
c
np.zeros((3, 4))
np.ones((2, 2, 2))
np.empty((2, 3))

array([[1.804772e-316, 0.000000e+000, 0.000000e+000],
       [0.000000e+000, 0.000000e+000, 0.000000e+000]])

In [ ]:
A = np.arange(15).reshape(3, 5)
B = np.arange(15).reshape(3, 5)
C = A @ B.T
C.cumsum(0)
np.hstack((A, B))

array([[ 0,  1,  2,  3,  4,  0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 10, 11, 12, 13, 14]])

In [ ]:
def f(x, y):
    return 10 * x + y
b = np.fromfunction(f, (5, 4), dtype=int)
print(b)
b[2, 1:4]

[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]
 [40 41 42 43]]


array([21, 22, 23])

In [ ]:
a = np.arange(10)  ** 2
i = np.arange(10).reshape(2, -1)
a[i]

array([[ 0,  1,  4,  9, 16],
       [25, 36, 49, 64, 81]])

In [ ]:
a = np.arange(12).reshape(3, 4)
i = np.array([[0, 1],  # indices for the first dim of `a`
             [1, 2]])
j = np.array([[2, 1],  # indices for the second dim
             [3, 3]])
print(a)
print(a.shape[1])
a[i,j]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
4


array([[ 2,  5],
       [ 7, 11]])

In [ ]:
import numpy as np

import matplotlib.pyplot as plt

def mandelbrot(h, w, maxit=20):

    """Returns an image of the Mandelbrot fractal of size (h,w)."""

    y, x = np.ogrid[-1.4:1.4:h*1j, -2:0.8:w*1j]

    c = x + y * 1j

    z = c

    divtime = maxit + np.zeros(z.shape, dtype=int)


    for i in range(maxit):

        z = z**2 + c

        diverge = z * np.conj(z) > 2**2       # who is diverging

        div_now = diverge & (divtime == maxit)  # who is diverging now

        divtime[div_now] = i                    # note when

        z[diverge] = 2                          # avoid diverging too much


    return divtime

plt.imshow(mandelbrot(400, 400))
